- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    dotfiles:
      src:
        repository: "https://github.com/yusekiya/dotfiles.git"
      dest: "~/dotfiles"
      symlink_script: "sh setup.sh -f"

    homebrew_taps:
      - caskroom/cask
      - caskroom/fonts
      - railwaycat/emacsmacport

    homebrew_packages:
      - { name: ansible}
      - { name: ag }
      - { name: aspell }
      - { name: autoconf }
      - { name: automake }
      - { name: xz }
      - { name: binutils }
      - { name: bash-completion }
      - { name: cmake }
      - { name: colordiff }
      - { name: coreutils }
      - { name: ctags }
      - { name: direnv }
      - { name: ffmpeg }
      - { name: findutils }
      - { name: fzf }
      - { name: gawk}
      - { name: ghostscript }
      - { name: git }
      - { name: gnutls }
      - { name: gnu-sed, install_options: with-default-names }
      - { name: imagemagick }
      - { name: nkf }
      - { name: lua }
      - { name: pandoc }
      - { name: peco }
      - { name: pstoedit }
      - { name: ssh-copy-id }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: vim, install_options: with-lua }
      - { name: emacs-mac, install_options: with-modern-icon }
      - { name: nodebrew }

    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: xquartz }
      - { name: atom }
      - { name: dropbox }
      - { name: font-fontawesome }
      - { name: skim}
      - { name: adobe-reader }
      - { name: mendeley-desktop }
      - { name: karabiner}
      - { name: mactex}

    basic_dirs:
        - { path: "{{ lookup('env', 'HOME') }}/.nodebrew/src",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/.brewland",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/bin",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/scratch",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/share",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/Documents/AcademicConference",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/Documents/Fund",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/Documents/Seminar",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/Documents/Study",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/Documents/Misc",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/usr/bin",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/usr/include",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/usr/lib",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/usr/lib/python3/site-packages",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/usr/share",
            state: directory }
        - { path: "{{ lookup('env', 'HOME') }}/usr/src",
            state: directory }

    git_repos:
        - { name: tpm,
            repo: "https://github.com/tmux-plugins/tpm.git",
            dest: "~/.tmux/plugins/tpm" }
        - { name: solarized,
            repo: "https://github.com/altercation/solarized.git",
            dest: "~/repos/solarized" }
        - { name: dircolors-solarized,
            repo: "https://github.com/seebi/dircolors-solarized.git",
            dest: "~/repos/dircolors-solarized" }
        - { name: enhancd,
            repo: "https://github.com/b4b4r07/enhancd.git",
            dest: "~/repos/enhancd" }

  tasks:
    - name: create basic directories
      file:
          path: "{{ item.path }}"
          state: "{{ item.state }}"
      with_items: "{{ basic_dirs }}"

    - name: add repositories for homebrew
      homebrew_tap:
          tap: "{{ item }}"
          state: present
      with_items: "{{ homebrew_taps }}"

    - name: update homebrew
      homebrew:
          update_homebrew: yes

    - name: install homebrew packages
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('latest') }}"
        install_options: "{{ item.install_options | default(omit) }}"
      with_items: "{{ homebrew_packages }}"
      register: ret_homebrew

    - name: check updated homebrew package
      set_fact: updated_homebrew_package={{ ret_homebrew.results | selectattr('changed') | map(attribute='item.name') | list }}

    - name: install homebrew cask packages
      homebrew_cask:
          name: "{{ item.name }}"
          state: "{{ item.state | default('installed') }}"
      with_items: "{{ homebrew_cask_packages }}"
      register: ret_homebrew_cask

    - name: check updated homebrew cask package
      set_fact: updated_homebrew_cask_package={{ ret_homebrew_cask.results | selectattr('changed') | map(attribute='item.name') | list }}

    - name: link apps with homebrew
      command: brew linkapps
      when: (ret_homebrew | changed) or (ret_homebrew_cask | changed)

    - name: install dotfiles
      git:
          repo: "{{ dotfiles.src.repository }}"
          dest: "{{ dotfiles.dest }}"
      register: ret_git_dotfiles
      # Uncomment the following line if git module always returns state changed
      # changed_when: "ret_git_dotfiles.after|default('after') != ret_git_dotfiles.before|default('before')"

    - name: symlink dotfiles
      shell: "{{ dotfiles.symlink_script }}"
      args:
          chdir: "{{ dotfiles.dest }}"
      when: ret_git_dotfiles | changed

    - name: install fzf auto complete and key bindings
      shell: /usr/local/opt/fzf/install --key-bindings --completion --no-update-rc
      when: "{{ 'fzf' in updated_homebrew_package }}"

    - name: clone git repositories
      git:
          repo: "{{ item.repo }}"
          dest: "{{ item.dest }}"
      with_items: "{{ git_repos }}"
      register: ret_git_clone

    - name: downlowd .envrc for brewland
      get_url:
          url: "https://gist.githubusercontent.com/yusekiya/c38cb5216084365273af117b99a42472/raw/dfb51ec9b2c4353eb1a81b223122e510f94d53d9/.envrc"
          dest: "{{ lookup('env', 'HOME') }}/.brewland/.envrc"

