- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    dotfiles:
      src:
        repository: "https://github.com/yusekiya/dotfiles.git"
      dest: "~/dotfiles"
      symlink_script: "sh setup.sh -f"

    homebrew_taps:
      - caskroom/cask
      - caskroom/fonts
      - railwaycat/emacsmacport

    homebrew_packages:
      - { name: ansible}
      - { name: ag }
      - { name: aspell }
      - { name: autoconf }
      - { name: automake }
      - { name: xz }
      - { name: binutils }
      - { name: bash-completion }
      - { name: cmake }
      - { name: colordiff }
      - { name: coreutils }
      - { name: ctags }
      - { name: direnv }
      - { name: ffmpeg }
      - { name: findutils }
      - { name: fzf }
      - { name: gawk}
      - { name: ghostscript }
      - { name: git }
      - { name: gnutls }
      - { name: gnu-sed, install_options: with-default-names }
      - { name: imagemagick }
      - { name: nkf }
      - { name: lua }
      - { name: pandoc }
      - { name: peco }
      - { name: pstoedit }
      - { name: ssh-copy-id }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: vim, install_options: with-lua }
      - { name: emacs-mac, install_options: with-modern-icon }
      - { name: nodebrew }

    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: xquartz }
      - { name: atom }
      - { name: dropbox }
      - { name: font-fontawesome }
      - { name: skim}
      - { name: adobe-reader }
      - { name: mendeley-desktop }
      - { name: karabiner}
      - { name: mactex}

  tasks:
    - name: add repositories
      homebrew_tap:
          tap: "{{ item }}"
          state: present
      with_items: "{{ homebrew_taps }}"

    - name: update homebrew
      homebrew:
          update_homebrew: yes

    - name: install homebrew packages
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('latest') }}"
        install_options: "{{ item.install_options | default(omit) }}"
      with_items: "{{ homebrew_packages }}"
      register: ret_homebrew

    - name: check updated homebrew package
      set_fact: updated_homebrew_package={{ ret_homebrew.results | selectattr('changed') | map(attribute='item.name') | list }}

    - name: install homebrew cask packages
      homebrew_cask:
          name: "{{ item.name }}"
          state: "{{ item.state | default('installed') }}"
      with_items: "{{ homebrew_cask_packages }}"
      register: ret_homebrew_cask

    - name: check updated homebrew cask package
      set_fact: updated_homebrew_cask_package={{ ret_homebrew_cask.results | selectattr('changed') | map(attribute='item.name') | list }}

    - name: link apps with homebrew
      command: brew linkapps
      when: (ret_homebrew | changed) or (ret_homebrew_cask | changed)

    - name: install dotfiles
      git:
          repo: "{{ dotfiles.src.repository }}"
          dest: "{{ dotfiles.dest }}"
      register: ret_git_dotfiles
      # changed_when: "ret_git_dotfiles.after|default('after') != ret_git_dotfiles.before|default('before')"

    - name: symlink dotfiles
      shell: "{{ dotfiles.symlink_script }}"
      args:
          chdir: "{{ dotfiles.dest }}"
      when: ret_git_dotfiles | changed

    - name: install fzf auto complete and key bindings
      shell: /usr/local/opt/fzf/install --key-bindings --completion --no-update-rc
      when: "{{ 'fzf' in updated_homebrew_package }}"

    - name: install tmux plugin manager
      git:
          repo: "https://github.com/tmux-plugins/tpm.git"
          dest: "~/.tmux/plugins/tpm"
      # register: ret_git_tmux
      # changed_when: "ret_git_tmux.after|default('after') != ret_git_tmux.before|default('before')"

    - name: download solarized theme
      git:
          repo: "https://github.com/altercation/solarized.git"
          dest: "~/repos/solarized"
      # register: ret_git_solarized
      # changed_when: "ret_git_solarized.after|default('after') != ret_git_solarized.before|default('before')"

    - name: download solarized colors for gnu ls
      git:
          repo: "https://github.com/seebi/dircolors-solarized.git" 
          dest: "~/repos/dircolors-solarized"
      # register: ret_git_gnuls_color
      # changed_when: "ret_git_gnuls_color.after|default('after') != ret_git_gnuls_color.before|default('before')"

    - name: install enhancd
      git:
          repo: "https://github.com/b4b4r07/enhancd"
          dest: "~/repos/enhancd"
      # register: ret_git_enhancd
      # changed_when: "ret_git_enhancd.after|default('after') != ret_git_enhancd.before|default('before')"

    - name: make directory for nodebrew
      file:
          path: "{{ lookup('env', 'HOME') }}/.nodebrew/src"
          state: directory

    - name: make brewland
      file:
          path: "{{ lookup('env', 'HOME') }}/.brewland"
          state: directory

    - name: downlowd .envrc for brewland
      get_url:
          url: "https://gist.githubusercontent.com/yusekiya/c38cb5216084365273af117b99a42472/raw/dfb51ec9b2c4353eb1a81b223122e510f94d53d9/.envrc"
          dest: "{{ lookup('env', 'HOME') }}/.brewland/.envrc"

