- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    dotfiles:
      src:
        repository: https://github.com/yusekiya/dotfiles.git
      dest: ~/dotfiles
      symlink_script: "~/dotfiles/setup.sh -f"

    homebrew_taps:
      - caskroom/cask
      - caskroom/fonts
      - railwaycat/emacsmacport

    homebrew_packages:
      - { name: ag }
      - { name: aspell }
      - { name: autoconf }
      - { name: automake }
      - { name: xz }
      - { name: binutils }
      - { name: bash-completion }
      - { name: cmake }
      - { name: colordiff }
      - { name: coreutils }
      - { name: ctags }
      - { name: direnv }
      - { name: ffmpeg }
      - { name: findutils }
      - { name: ghostscript }
      - { name: git }
      - { name: gnutls }
      - { name: imagemagick }
      - { name: nkf }
      - { name: lua }
      - { name: pandoc }
      - { name: peco }
      - { name: pstoedit }
      - { name: ssh-copy-id }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: vim, install_options: with-lua }
      - { name: emacs-mac, install_options: with-modern-icon }

    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: xquartz }
      - { name: atom }
      - { name: dropbox }
      - { name: font-fontawesome }
      - { name: inkscape }

  tasks:
    - name: add repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: update homebrew
      homebrew: update_homebrew=yes

    - name: install homebrew packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages

    - name: install homebrew cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages

    - name: install karabiner
      homebrew_cask: name=karabiner state=installed
      notify: setup karabiner

    - name: install mactex
      homebrew_cask: name=mactex state=installed
      notify: setup tex

    - name: install dotfiles
      git: repo={{ dotfiles.src.repository }} dest={{ dotfiles.dest }}
      register: ret_git_dotfiles
      when: dotfiles.src.repository

    - name: symlink dotfiles
      shell: sh {{ dotfiles.symlink_script }} chdir={{ dotfiles.dest }}
      when: ret_git_dotfiles|changed

    - name: install tmux plugin manager
      git: repo=https://github.com/tmux-plugins/tpm.git dest=~/.tmux/plugins/tpm

    - name: download solarized theme
      git: repo=https://github.com/altercation/solarized.git dest=~/repos/solarized

    - name: download solarized colors for gnu ls
      git: repo=https://github.com/seebi/dircolors-solarized.git dest=~/repos/dircolors-solarized

  handlers:
    - name: setup karabiner
      shell: sh karabiner-setup.sh chdir={{ inventory_dir }}
      args:
        removes: karabiner-setup.sh

    - name: setup tex
      shell: sudo tlmgr update --self --all

